"""add_explicit_fk_constraint_names

Revision ID: 0ce2bfad58fc
Revises: 4b74212dd106
Create Date: 2026-03-31 12:08:53.222249
"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "0ce2bfad58fc"
down_revision: str | Sequence[str] | None = "4b74212dd106"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
